{% set version = "8.2" %}
{% set name = "genutil" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/cdat/genutil/archive/v{{ version }}.tar.gz
    sha256: 171dd39dbcd814995f59eec5a23646cae12c08e5ef2e0e9c986198e220d2d038

build:
    number: 1
    skip: true  # [win]
 
requirements:
    build:
        - {{ compiler("c") }}
    host:
        - python {{ python }}
        - setuptools
        - numpy
        - udunits2
    run:
        - python {{ python }}
        - cdms2 >=3.1.3
        - udunits2
        - {{ pin_compatible('numpy') }}

test:
    commands:
        -  export CDAT_ANONYMOUS_LOG=false && python -c "import genutil"

about:
    home:  http://github.com/CDAT/genutil
    license: BSD
    license_file: bsd-3-clause.txt
    summary: 'General Utitilites for the Community Data Analysys Tools'

extra:
    recipe-maintainers:
        - doutriaux1
        - dnadeau4
        - xylar
        - downiec
        - muryanto1
