{% set version = "8.1.1" %}
{% set name = "genutil" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/cdat/genutil/archive/v8.1.tar.gz
    sha256: 7c12f2fc830672b14b15c9f91d0e955bb8474c0c8819a00b605b5ec94edd1649

build:
    number: 0
    skip: true  # [win]
 
requirements:
    build:
        - {{ compiler("c") }}
    host:
        - python {{ python }}
        - setuptools
        - numpy
        - udunits2
        - cdms2
    run:
        - python {{ python }}
        - cdms2
        - udunits2
        - {{ pin_compatible('numpy') }}

test:
    commands:
        -  export UVCDAT_ANONYMOUS_LOG=false && python -c "import genutil"

about:
    home:  http://gitub.com/CDAT/genutil
    license: 'CCLRC'
    license_file: LEGAL.txt
    summary: 'General Utitilites for the Community Data Analysys Tools'

extra:
    recipe-maintainers:
        - doutriaux1
        - dnadeau4
        - xylar
