{% set version = "8.2.1" %}
{% set name = "genutil" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/cdat/genutil/archive/v{{ version }}.tar.gz
    sha256: 944ccc4de05072d2773cfff6b5f279e2058457a672169153ebec0e19f5a3601c
    patches:
      - 0001-numpy-float-int.patch

build:
    number: 5
    skip: true  # [win or py>=311]
    script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
    build:
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
    host:
        - python
        - pip
        - cdms2
        - cython
        - expat
        - numpy
        - udunits2
    run:
        - python
        - cdms2
        - numpy

test:
    imports:
        - genutil

about:
    home:  http://github.com/CDAT/genutil
    license: BSD-3-Clause
    license_file: bsd-3-clause.txt
    summary: 'General Utitilites for the Community Data Analysys Tools'

extra:
    recipe-maintainers:
        - doutriaux1
        - dnadeau4
        - xylar
        - downiec
        - jasonb5
        - forsyth2
