{% set version = "8.2.1.rc2" %}
{% set name = "genutil" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/cdat/genutil/archive/v{{ version }}.tar.gz
    sha256: 4635bc8d5b7b60be9baf24bd413b117567c4e7180cb2efaa132a4fe13f40990a

build:
    number: 0
    skip: true  # [win]

requirements:
    build:
        - {{ compiler("c") }}
    host:
        - python
        - pip
        - cython
        - numpy
        - udunits2
        - cdms2
    run:
        - python
        - cdms2
        - udunits2
        - {{ pin_compatible('numpy') }}

test:
    commands:
        - python -c "import genutil"

about:
    home:  http://github.com/CDAT/genutil
    license: BSD
    license_file: bsd-3-clause.txt
    summary: 'General Utitilites for the Community Data Analysys Tools'

extra:
    recipe-maintainers:
        - doutriaux1
        - dnadeau4
        - xylar
        - downiec
        - muryanto1
        - jasonb5
        - forsyth2
