{% set name = "genutil" %}
{% set version = "8.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/UV-CDAT/genutil/archive/v{{ version }}.tar.gz
    sha256: 7c12f2fc830672b14b15c9f91d0e955bb8474c0c8819a00b605b5ec94edd1649


build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - numpy  1.11.*
    - udunits2
    - toolchain  # [osx]
  run:
    - python
    - cdms2
    - numpy >=1.11
    - udunits2

test:
    commands:
        - export UVCDAT_ANONYMOUS_LOG=false && python -c "import genutil"

about:
    home:  http://gitub.com/UV-CDAT/genutil
    license: 'CCLRC'
    summary: 'General Utitilites for the Community Data Analysys Tools'

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
