travis:
  secure:
    BINSTAR_TOKEN: PQSPqn5ve8Be0zHdBhq4iKQphJLZu+uFo2SmnKELyzUL6w4qYLx1lkGF0ECN5pEmGYgdr4ESztuz9ds8Q6qrk3f51kqaZLWHdet9hn5yvVmv8OGVeBxpaDQ8Jso8bfAZS5J4AoeXdJ2UfL2fBpgSPg8ALLIMNVzu13HAmauASpbToeytRCyszXv4y0500t9+i0tLT9Evfcn5DXvspxcO4EBmOX3FG/dt/UUM89VfOYun/fYfQeRcFD5V2emngvyXu6Z0w4xX1Ulg4sC2KTFfGEQuOhh1JLZjXHUzYb+BG0ETvTyx7y1b9Kk6/xupW82479D6aQdGTFJVJKaN2rDD2n1RBrH2EbPcQHw7OSgKAJWcb/BJXpEKOt72bdp7KzkrwD06crX3qeRzMp2Lck0JzuA1j1kEISJqkdCISEzYzJlUrtmLG/Il0eXmkC9VSz+NDZN1p1SEKJFjvcCpTfdi7VBoAfrRfxdmcisZK7UXX/qANMEi1NiYFkNSn7zhn1hoOgwsel2b+6oWI1ou7Li40wm6fCuaaHV4AKNWblX1SLsOI4QEXsuqciKBT+zEj4B+DbA0gTWBsj5GtFY+4r0zeXwfx8HTnsZh2TOPfURgjzmdvszoveWlmz/ZQc0fwXQ+K4D3KxZdVB6/wZgrfhGY+n1P5UO/77QiEuFr11FaHsk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
