travis:
  secure:
    BINSTAR_TOKEN: SqqGIvy4RYINGB5QiVVYJRzqWSK92CzeQbNPM7ckVNDe5D0MRKj+Eo+aw/lPVUWW7D5RRmxqiqhtDw10aV4i2xGU+6v1cMsWgL3RmmLm6UQRaACkGVJiKPGvj7MWisYFIiCKVu0ZG3DQUnGXXeuCfnddnuLRlAlbFUe/FcunlwD5eDFKjHNeltReumDRhIwT+3FyUhrLdOUOjO/rI6DZOvZskkd++7BKUiw0gO2zvW3Ux9WX32VCMrpHqbG1Ml80DuhU2O2zxg8N/CK/utoGeZwu3eiUGzYFSXVYZybPUHugXo35QlG6LKszEhq50PnDxg1SOh95+ZtUt43BI4HP7fLebdQfP/kftz5BtoszQ4w85nIaEqpou2Au+cnjpO72xHlt/kERN6dxjnrKl7G54RHprIwDT7KmrWZmEYBvcOMmSo9pwaNBI1pOIl5e6JNUTXmKWY1LZ9NsfKBGFyAFMH125hPyt8kRaqGoUV1T73BHhH5tnh8zgs08guwBWw8EG7EcSJDb+p4mQ74cUBEN+0UgvXWC3pHygjAXS9pqDO/6nhrEQIxlXt2MJk3EwWI7QWwDpYdKuvoT0ydkWpx2KYG3qTPqD/Q9/ep62vPYJDQK6EqSGbdo+gA+JVUafHQDB8clWw4F2rXZ1dErfmspPo4jdmsOeSCfMPqLhlPnneQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
